### ISSUE TITLE
TypeError: Inheritance class AuthorizedSession from ClientSession is forbidden

### ISSUE THREAD

**Issue by rllin** [facebookresearch/torchsnapshot#34]
### 🐛 Describe the bug

Unsure where this is coming from, but this seems to be an innocuous call of `Snapshot.take` that worked on a fork from mid-June.  I tried to rebase with `torchsnapshot-nightly==2022.7.10` and got this:

```
Traceback (most recent call last):
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 152, in <module>
    app.run(main)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 144, in main
    maybe_run_training(
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/twitter/ml/torch/experimental/distributed/training.py", line 39, in maybe_run_training
    train_fn(**training_kwargs)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 118, in train
    train_and_evaluate(
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/custom_training_loop.py", line 161, in train_and_evaluate
    checkpoint_handler.save(global_step=step * dist.get_world_size())
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/checkpointing/snapshot.py", line 38, in save
    snapshot = torchsnapshot.Snapshot.take(
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torchsnapshot/snapshot.py", line 182, in take
    storage = url_to_storage_plugin_in_event_loop(
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torchsnapshot/storage_plugin.py", line 72, in url_to_storage_plugin_in_event_loop
    return event_loop.run_until_complete(_url_to_storage_plugin(url_path=url_path))
  File "/opt/ee/python/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torchsnapshot/storage_plugin.py", line 70, in _url_to_storage_plugin
    return url_to_storage_plugin(url_path=url_path)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torchsnapshot/storage_plugin.py", line 41, in url_to_storage_plugin
    from torchsnapshot.storage_plugins.gcs import GCSStoragePlugin
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torchsnapshot/storage_plugins/gcs.py", line 22, in <module>
    from google._async_resumable_media.requests import (  # @manual
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/google/_async_resumable_media/requests/__init__.py", line 661, in <module>
    from google._async_resumable_media.requests.download import ChunkedDownload
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/google/_async_resumable_media/requests/download.py", line 21, in <module>
    from google._async_resumable_media.requests import _request_helpers
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/google/_async_resumable_media/requests/_request_helpers.py", line 26, in <module>
    import google.auth.transport._aiohttp_requests as aiohttp_requests
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/google/auth/transport/_aiohttp_requests.py", line 196, in <module>
    class AuthorizedSession(aiohttp.ClientSession):
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 265, in __init_subclass__
    raise TypeError("Inheritance class {} from ClientSession "
TypeError: Inheritance class AuthorizedSession from ClientSession is forbidden
```

### Versions

torchsnapshot-nightly==2022.7.10
torch==1.12.0
torchrec==0.2.0

**Comment by yifuwang** [comment]
Hi @rllin, thanks for reporting the issue. Could you please share the `aiohttp` version in your environment?
